name: Multi-Cloud VM Start Stop

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Target cloud (aws | azure | gcp)"
        required: true
        default: "aws"
      action:
        description: "Action to perform (start | stop)"
        required: true
        default: "stop"

jobs:
  vm-control:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cloud Custodian
        run: |
          python -m pip install --upgrade pip
          pip install c7n

      # ---------------- AWS AUTH ----------------
      - name: Configure AWS credentials
        if: inputs.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          with:
    	    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  	    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 	    aws-region: ${{ secrets.AWS_REGION }}

      # ---------------- AZURE AUTH ----------------
      - name: Azure Login
        if: inputs.cloud == 'azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
    # ---------------- GCP AUTH ----------------
      - name: GCP Authentication
        if: inputs.cloud == 'gcp'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}}
      
     # ---------------- RUN CLOUD CUSTODIAN ----------------
      - name: Run Cloud Custodian policy
        run: |
          POLICY="policies/${{ inputs.cloud }}-${{ inputs.action }}.yml"
          echo "Running policy: $POLICY"
          custodian run $POLICY
